### ISSUE TITLE
Allow users to override localisation

### ISSUE THREAD

**Issue by grandwazir** [grandwazir/BanHammer#1]
This is the first step towards adding customised messages to BanHammer. We will most likely do this by writing out the localisation in use when we first start BanHammer to the plugin directory and then check to see if the user has added any overrides into this file.

We could check for this in two different ways, if a node exists use it or additionally load the entire file and check to see if the nodes are different to inbuilt localisation. 

Actually thinking about it do we even need to check if they are different?

**Comment by grandwazir** [comment]
Yes we do in case we add additional messages between versions which are not included in the current overrides. We can then throw warnings at the user to say they have an out of date localisation file or update it ourselves.

**Comment by JoneKone** [comment]
For some reason my BH doesn't output anything to chat when I pardon or ban somebody...
