### ISSUE TITLE
Add support for banning players by UUID

### ISSUE THREAD

**Issue by grandwazir** [grandwazir/BanHammer#100]
With the recent changes Mojang is making to Minecraft it will be necessary to restructure the database to store UUIDs rather than player names.

**Comment by Yrlish** [comment]
How is it going with this part?

**Comment by grandwazir** [comment]
It is pretty much finished and working in the experimental branch. I am just adding some other features as well before I release it and working out a way to migrate all old bans to the new system.

**Comment by Yrlish** [comment]
Great! :+1:

**Comment by Sharrq** [comment]
Im sure you are working hard on this, but I am wondering if there is an ETA on this, or if this was already added to a dev build?

The only reason I ask is because we are in the process of going through all of our plugins to determine if they have a UUID Update or not, and unfortunately our current Ban Plugin will not be updating to UUID so we are looking for a replacement. BanHammer seems to be the perfect replacement for us, but we dont want to make the switch until this has UUID implemented. Seeing as we arent currently using BanHammer, migrating old bans isnt as important to us. And since we are moving from one Ban System to another, we intend on wiping our ban list except for a few choice troublemakers which we can re-ban manually once we install BanHammer.

Not trying to be pushy, just wondering if you had an ETA :)

**Comment by grandwazir** [comment]
@Grasty I am always glad to see people using my work. It is still work in progress. I was rushing to do it for when 1.7 came out but then saw that the UUID integration was pushed back so I left it for a while. Since I am going to have to change the database schema anyway to support UUID I have taken the opportunity to add comments to bans and players as an additional feature. As for when it will be done I am hoping to have a beta build out in the next week for people to test. I won't most likely have the ability to migrate existing bans (that will come in the final release) but by the sounds of it you don't need it. The main message is that it is still supported and actively worked on. You can check out what is happening on the experimental branch if you want to follow the progress.

**Comment by Sharrq** [comment]
Thanks for the quick response :) I am willing to test it for you once you have it ready.

**Comment by grandwazir** [comment]
This is in and now working on the experimental branch. I'll let you know when there is a build available for testing; I've still got to test and debug the other commands before releasing a beta build.

**Comment by QueueAmI** [comment]
I'm taking a look at your experimental code. I was going to try it out on a test server, but I will eventually need to migrate an existing database. Any thoughts on when you may have code to assist with this? I'm a little new to java coding, but I may take a crack at it on my own as time allows.

**Comment by grandwazir** [comment]
The code to migrate databases is pretty much there as far as I remember but it hasn't been tested thoroughly. If anyone has a database then can send me to use for testing purposes that would be excellent. 

I am looking for people to help maintain my projects. If you are interested in helping I can go through the code with you and the things that need doing. The database specific stuff is rather convoluted; not least as I have to work around numerous issues with Bukkit's implementation of EBean and EBean lack of support for schema upgrades.

**Comment by QueueAmI** [comment]
Hmm, I couldn't find anything specific to go through and convert an old database in the experimental code. I did manage to get the experimental version to run, but I had to fix a small bug in one of the test modules where you had not specified the "Type" of comment to be a "BAN_REASON". After fixing that, everything compiled and runs perfectly as far as I can tell.

I've put together a small C# application that is converting my database to the new format. I was even able to (easily) retrieve the UUIDs from Mojang.

I can certainly take a look at certain changes or problems if you need help. As I said, I'm not real good with java yet, but I'm learning.
