### ISSUE TITLE
Modify PurgeCommand to optionally only purge last ban made

### ISSUE THREAD

**Issue by grandwazir** [grandwazir/BanHammer#11]
This is a requirement to allow bans which have been pardoned early to still be available in the database.

**Comment by ryans1230** [comment]
You could add like a purgelast command and tie it into the ban.\* permission. I like how all bans are now on record, regardless if they are pardoned or not, but my Mods keep making mistakes and its become hard to manage. So if you could please make it part of banhammer.ban.*, that would be great.

**Comment by grandwazir** [comment]
I was thinking on modelling it like the pardon command, with purge own and others with an additional option to purge all bans.

So if you wanted to delete the last ban you made you would type `/bh purge fred` and if you wanted to purge all bans you would to `/bh purge -A Fred.
