### ISSUE TITLE
UUID Support?

### ISSUE THREAD

**Issue by Permanently** [grandwazir/BanHammer#126]
Hi,
when will you add UUID support to BanHammer? I love this plugin and I really want this to be added c:
Thanks

**Comment by grandwazir** [comment]
It is already implemented in the latest beta version. Did you try that?

**Comment by Permanently** [comment]
I can't find it... :/

**Comment by Permanently** [comment]
...?

**Comment by Permanently** [comment]
Update: I never found that beta version.
