### ISSUE TITLE
Ban Glitch: Bans Players

### ISSUE THREAD

**Issue by Silvertraveler123** [grandwazir/BanHammer#16]
I have recently gotten banned from a server, and no not by a staff member, but by a hacker or glitch, the staff members and owner looked in their files and found no ban records for me. This leads me to believe that there is some freaky kind of glitch, or it makes security in servers have flaws, I tried to go to the server once a day, but the problem still hasn't been resolved, and it continues to say "The Ban Hammer has spoken!". Could you check your plugin to look for anything that may have caused the issue, and resolve it? If so thank you, I don't think any less of you even though this glitch bothers me hugely.

**Comment by grandwazir** [comment]
BanHammer has spoken is not my plugin it is another with the same name. I can not help you I am afraid.
