### ISSUE TITLE
Ban the wrong player

### ISSUE THREAD

**Issue by MarioG1** [grandwazir/BanHammer#22]
The player name matching function isn't working correct. If you try to ban one person it banns another person.

An example:

ProGamer99 and PandaMan play on my server. Now it ban Progamer99 with 
/ban ProGamer99 t:1h Spamming but the player name matching function ban's now PandaMan instead of ProGamer99.

**Comment by grandwazir** [comment]
Does this happen with the latest BanHammer version? Can you duplicate it every time?

**Comment by MarioG1** [comment]
I had some intensive testing on my server and i wasn't able to reproduce this error. I think it is fixed now :)

**Comment by grandwazir** [comment]
Ok, thanks for letting me know. I'll close this issue now.
