### ISSUE TITLE
Permissions

### ISSUE THREAD

**Issue by ryans1230** [grandwazir/BanHammer#25]
Hello,
I have installed banhammer on my server and there are some few issues having players with no permission of the banhammer nodes.
Yet they still have access to use /bh history and /bh limits, I'm wondering if this is a bug due to your plugin if not may I please have some assistance on this issues. The plugins I have used to organize the permissions is Essentials and GroupManager
Thanks, Heinrich.

**Comment by grandwazir** [comment]
This would make sense since those commands are available to everyone by default. I would think that your permission settings are not being applied correctly. Could you post your group manager config? Also try turning on debugging in the BanHammer configuration; this may help narrow things down.

**Comment by ryans1230** [comment]
Here is my group.yml

# Group inheritance

# any inherited groups prefixed with a g: are global groups

# These groups are defined in the globalgroups.yml

# and can be inherited in any worlds groups/users.yml.

#

# Groups without the g: prefix are groups local to this world

# and defined in the this groups.yml file.

groups:
  Owner:
    default: false
    permissions:
    - '_'
    - essentials.spawn
    - spectate.cantspectate
    - spectate.use
    - item.use.lavabucket
    - item.use.waterbucket
    - item.use.flintandsteel
    - item.use.tnt
    - item.use.firecharge
    inheritance:
    - admin
    info:
      prefix: '[&cOwner&f] '
      build: true
      suffix: '&f'
  Mod:
    default: false
    permissions:
    - vanish.vanish
    - essentials.afk
    - essentials.back
    - essentials.balance
    - essentials.balancetop
    - essentials.ban
    - essentials.fly
    - essentials.god
    - essentials.help
    - essentials.helpop
    - essentials.home
    - essentials.home.others
    - essentials.ignore
    - essentials.kick
    - essentials.kit._
    - essentials.kit.Dtools.tools
    - essentials.kit.mod
    - essentials.list
    - essentials.motd
    - essentials.msg
    - essentials.near
    - essentials.pay
    - essentials.rules
    - essentials.sethome
    - essentials.spawn
    - essentials.suicide
    - essentials.tp
    - essentials.tphere
    - essentials.warp
    - essentials.warp.list
    - essentials.who
    - ExtraFlight.avoidKick
    - ExtraFlight.RememberMode
    - ExtraFlight.UseFlight
    - ExtraFlight.UseFlight.Others
    - logblock.rollback
    - logblock.lookup
    - logblock.tp
    - logblock.spawnTools
    - lwc.*
    - nocheat.checks.moving.flying
    - essentials.seen
    - item.use.lavabucket
    - item.use.waterbucket
    - item.use.flintandsteel
    - item.use.firecharge
    - banhammer.ban.permanent
    - banhammer.history
    - banhammer.history.others
    - banhammer.kick
    - banhammer.pardon
    - banhammer.pardon.all
    - essentials.mail
    inheritance:
    - new
    - member
    - trusted
    info:
      prefix: '[&3Mod&f] &3'
      build: true
      suffix: '&f'
  Member:
    default: false
    permissions:
    - essentials.afk
    - essentials.back
    - essentials.balance
    - essentials.balancetop
    - essentials.help
    - essentials.helpop
    - essentials.home
    - essentials.home.others
    - essentials.ignore
    - essentials.kit
    - essentials.kit.dtools
    - essentials.kit.tools
    - essentials.list
    - essentials.motd
    - essentials.msg
    - essentials.near
    - essentials.pay
    - essentials.rules
    - essentials.sethome
    - essentials.spawn
    - essentials.suicide
    - essentials.warp
    - essentials.warp.list
    - essentials.who
    - ^logblock.\* 
    - essentials.seen
    - ^banhammer.ban.*
    - ^banhammer.history
    - ^banhammer.history.others
    - ^banhammer.limits
    - essentials.mail
    inheritance:
    - new
    info:
      prefix: '&7Member: &7'
      build: true
      suffix: '&f'
  Operator:
    default: false
    permissions:
    - vanish.vanish
    - banhammer.*
    - essentials.afk
    - essentials.back
    - essentials.balance
    - essentials.balancetop
    - essentials.ban
    - essentials.gamemode
    - essentials.god
    - essentials.help
    - essentials.home
    - essentials.home.others
    - essentials.ignore
    - essentials.kick
    - essentials.kit.New
    - essentials.list
    - essentials.motd
    - essentials.msg
    - essentials.near
    - essentials.pay
    - essentials.rules
    - essentials.sethome
    - essentials.signs.use.*
    - essentials.spawn
    - essentials.suicide
    - essentials.teleport.timer.bypass
    - essentials.tempban
    - essentials.tempban.offline
    - essentials.tp
    - essentials.tpa
    - essentials.tpaccept
    - essentials.tpohere
    - essentials.tptoggle
    - essentials.unban
    - essentials.warp
    - essentials.warp.list
    - essentials.who
    - logblock.*
    - spectate.use
    - worldedit.*
    - essentials.seen
    - item.use.lavabucket
    - item.use.waterbucket
    - item.use.flintandsteel
    - item.use.firecharge
    - banhammer.ban.permanent
    - banhammer.history
    - banhammer.history.others
    - banhammer.kick
    - banhammer.pardon
    - banhammer.pardon.all
    - essentials.mail
    inheritance:
    - new
    - member
    - trusted
    - mod
    info:
      prefix: '[&aOperator&f] &a'
      build: true
      suffix: '&f'
  New:
    default: true
    permissions:
    - essentials.afk
    - essentials.back
    - essentials.balance
    - essentials.balancetop
    - essentials.help
    - essentials.helpop
    - essentials.home
    - essentials.home.others
    - essentials.ignore
    - essentials.kit
    - essentials.kit.dtools
    - essentials.kit.Dtools.tools
    - essentials.kit.tools
    - essentials.list
    - essentials.motd
    - essentials.msg
    - essentials.near
    - essentials.pay
    - essentials.rules
    - essentials.sethome
    - essentials.spawn
    - essentials.suicide
    - essentials.warp
    - essentials.warp.list
    - essentials.who
    - kit.*
    - ^logblock.\* 
    - essentials.seen
    - ^banhammer.ban.*
    - ^banhammer.history
    - ^banhammer.history.others
    - ^banhammer.limits
    - essentials.mail
    inheritance: []
    info:
      prefix: '&fNew: &f'
      build: true
      suffix: '&f'
  Trusted:
    default: false
    permissions:
    - essentials.afk
    - essentials.back
    - essentials.balance
    - essentials.balancetop
    - essentials.help
    - essentials.helpop
    - essentials.home
    - essentials.home.others
    - essentials.ignore
    - essentials.kit
    - essentials.kit.dtools
    - essentials.kit.Dtools.tools
    - essentials.kit.tools
    - essentials.list
    - essentials.motd
    - essentials.msg
    - essentials.near
    - essentials.pay
    - essentials.rules
    - essentials.sethome
    - essentials.spawn
    - essentials.suicide
    - essentials.warp
    - essentials.warp.list
    - essentials.who
    - ^logblock.\* 
    - essentials.seen
    - item.use.waterbucket
    - ^banhammer.ban.*
    - ^banhammer.history
    - ^banhammer.history.others
    - ^banhammer.limits
    - essentials.mail
    inheritance:
    - new
    - member
    info:
      prefix: '[&6Trusted&f] &6'
      build: true
      suffix: '&f'
  Admin:
    default: false
    permissions:
    - vanish.vanish
    - -bukkit.command.op.give
    - -bukkit.command.op.take
    - '_'
    - banhammer._
    - essentials.afk
    - essentials.back
    - essentials.balancetop
    - essentials.home.others
    - essentials.ignore
    - essentials.rules
    - essentials.sethome
    - essentials.spawn
    - essentials.suicide
    - logblock.*
    - spectate.use
    - worldedit.*
    - worldguard.*
    - item.use.lavabucket
    - item.use.waterbucket
    - item.use.flintandsteel
    - item.use.tnt
    - item.use.firecharge
    - banhammer.ban.permanent
    - banhammer.history
    - banhammer.history.others
    - banhammer.kick
    - banhammer.pardon
    - banhammer.pardon.all
    inheritance:
    - operator
    info:
      prefix: '[&9Admin&f] &9'
      build: true
      suffix: '&f'
And debugging is set to :true :/

**Comment by grandwazir** [comment]
Your permissions file looks fine. I am not sure where the issue lies.

Try disabling all other plugins other than BanHammer and GroupManager, simplify your permissions file and then see if it works.

**Comment by ryans1230** [comment]
Ok. Now we have an issue with the ".notify" node. I have given it to moderators so they know who gets banned by other mods. We have noticed that some players are getting the notification message when a player is banned/kicked. From our studies, it appears that a group, "Trusted" (the rank below moderator), can see them. Is this an issue with the inheritance or does the ".notify" node apply to every rank?

**Comment by grandwazir** [comment]
From you permission file above it doesn't seem you are giving anyone that permission. If you turn on debugging, the log should tell you what the default permission mode is for that node on startup.
