### ISSUE TITLE
Adding Bans to the History

### ISSUE THREAD

**Issue by Moepfel1995** [grandwazir/BanHammer#26]
It is possible that you add in the /bh history a history of kicks,bans and tempbans?
it would be very cool.

**Comment by grandwazir** [comment]
BanHammer already tracks temporary bans and permanent bans in the history. Are you asking for kicks to be added to that list as well?

**Comment by Moepfel1995** [comment]
yes i know it tracks temporary bans but not full bans when we pardon someone is it not written in the history and kicks in the history are good too
