### ISSUE TITLE
Kick Broadcast

### ISSUE THREAD

**Issue by bigdogdk** [grandwazir/BanHammer#27]
When kicking players for some reason it doesn't broadcast it on the server. Do we have a setting wrong or is that not implemented? It would help if it would broadcast kicks so someone isn't kick multiple time for doing something.

**Comment by grandwazir** [comment]
Notifications are sent to people who have the "banhammer.notify" permission. Have you assigned that permission?

**Comment by bigdogdk** [comment]
"bannhammer.notify" is assigned. bans are broadcasting but not kicks. if it helps we are using 1.10.2

**Comment by grandwazir** [comment]
I'll look into it. It should be doing the same for kicks.

**Comment by bigdogdk** [comment]
I looked at the code (I'm not very good with java yet) but I didn't see anything about broadcasting kicks as if you had accidently removed it.

**Comment by bigdogdk** [comment]
Just updated plugin on server and kicks are still not being broadcasted to everyone.

**Comment by xLRDx** [comment]
Hmm bigdogdk is right there is only a notify for bans maybe change your ticket to a feature :]

**Comment by bigdogdk** [comment]
Thank you for fixing this.
