### ISSUE TITLE
Adding location to the history

### ISSUE THREAD

**Issue by Moepfel1995** [grandwazir/BanHammer#28]
Hello,

Can you please add the option to save locations to the history? Often we dont know what the banned player did exact, and when we see this location again, we can decide much better.

**Comment by grandwazir** [comment]
This is unlikely to happen. How would BanHammer decide what location to log? What happens if you then rollback the damage later and the proof is gone?

**Comment by grandwazir** [comment]
Closed due to lack of activity.
