### ISSUE TITLE
Doesn't work with permissions 3.1.6

### ISSUE THREAD

**Issue by metalozedex** [grandwazir/BanHammer#3]
sorry I posted it a while ago on the forum thread, I used the command /pr metalozedex has banhammer.ban and it said I did have that permission but when I try to execute it ingame it says I don't have the permission...

here's the file in .rar it has the group and user files from permission
http://www.mediafire.com/?k84dm5m7ahmax4j
if you want to snoop around and check if it's in order...

by the way I did put weights and even with the '*' it doesn't work :S

again thanks for your time

**Comment by grandwazir** [comment]
Permissions API support was removed from BanHammer 1.5.0. If you still wish to use Permissions 3.1.6, you can use any version before 1.5.0.
