### ISSUE TITLE
Pardoning with MySQL results in a server crash

### ISSUE THREAD

**Issue by Plehix** [grandwazir/BanHammer#34]
Hi, I'm using BanHammer 2.0.2 with a MySQL database setup and when pardoning a player, the server crashes with this report:
http://ipwnage.com/stuff/crash-2012-08-24_21.36.33-server.txt

The player doesn't seem to be unbanned, rather a duplicate entry of his ban seems to be entered into the database when issuing this command: http://ipwnage.com/stuff/bhdb.PNG

The plugins currently being used: Plugins (40): TimTheEnchanter, WorldGenerationControl, LagMeter, WorldEdit, NoCheatPlus, SimpleFly, ChatCo, CommandBook, LogBlockQuestioner, Sewers, Multiverse-Core, BanHammer, PermissionsEx, LogBlock, MyHome, WorldGuard, dynmap, LazyRoad, iConomy, PetitionPlugin2, CraftBookCommon, OpenInv, DrugMeUp, ScheduledAnnouncer2, SupplySign, Votifier, MyWarp, CraftBookCircuits, Facepalm, MagicCarpet, VanishNoPacket, Superpickaxe, CraftBookVehicles, CraftBookMechanisms, WirelessRedstone, Vault, LWC, GB.Shopper, MonsterBox, Herochat

Any idea?

**Comment by grandwazir** [comment]
This is a bug which was in the 2.0.0 snapshot, the result of which is the player is saved twice into the database by accident. This results in this error.

To fix it you first need to find the duplicate player in you ban hammer_players table and delete it. Additionally you will need to delete any other reference to that ID in ban hammer_bans and banhamer_player_bans.

A quicker fix is to rename the player to something else which is unique, then you can use the in game command to sort the rest of it out.

**Comment by Plehix** [comment]
I've reverted back to a 1.10 release as I just prefer it. Restored my old
DB and can use my ban page again.

Thanks, though.
