### ISSUE TITLE
Ban reason missing

### ISSUE THREAD

**Issue by ciulic** [grandwazir/BanHammer#35]
Hi
when you ban somebody with /ban nick t:10m any_reason that person can see the reason but if he tries to reconnect
he is seeing only the time and NO REASON.

Is this something that can be fixed?

**Comment by grandwazir** [comment]
Currently I am limited with the amount of text available on that screen. There is not enough space (last time I tried) to put the time and the reason. 

Could you suggest a format you would like?

**Comment by ciulic** [comment]
I think the format I would like to have/see is something like this:
"reason" - 205 hours 43 minutes remaining
I really don't know what is the characters limit, but what is most important, obviously, is the Reason.

Best Regards.
