### ISSUE TITLE
Conflict with SimpleMail?

### ISSUE THREAD

**Issue by Brottweiler** [grandwazir/BanHammer#37]
When having BanHammer and SimpleMail installed at the same time, this error appears.

SimpleMail: http://dev.bukkit.org/server-mods/odium-simplemail/

[SEVERE] java.lang.NullPointerException
[SEVERE]    at name.richardson.james.bukkit.banhammer.BanHammer.registerCommands(BanHammer.java:167)
[SEVERE]    at name.richardson.james.bukkit.banhammer.utilities.plugin.AbstractPlugin.onEnable(AbstractPlugin.java:105)
[SEVERE]    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:217)
[SEVERE]    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:374)
[SEVERE]    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:381)
[SEVERE]    at org.bukkit.craftbukkit.CraftServer.loadPlugin(CraftServer.java:285)
[SEVERE]    at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:267)
[SEVERE]    at org.bukkit.craftbukkit.CraftServer.reload(CraftServer.java:593)
[SEVERE]    at org.bukkit.Bukkit.reload(Bukkit.java:183)
[SEVERE]    at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:21)
[SEVERE]    at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:168)
[SEVERE]    at org.bukkit.craftbukkit.CraftServer.dispatchCommand(CraftServer.java:517)
[SEVERE]    at org.bukkit.craftbukkit.CraftServer.dispatchServerCommand(CraftServer.java:509)
[SEVERE]    at net.minecraft.server.DedicatedServer.ai(DedicatedServer.java:249)
[SEVERE]    at net.minecraft.server.DedicatedServer.q(DedicatedServer.java:214)
[SEVERE]    at net.minecraft.server.MinecraftServer.p(MinecraftServer.java:474)
[SEVERE]    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:405)
[SEVERE]    at net.minecraft.server.ThreadServerApplication.run(SourceFile:539)

**Comment by grandwazir** [comment]
Works correctly on my system with the latest version of both plugins. Please reopen if you are still encountering problems.
