### ISSUE TITLE
Purge Command Does Not Work

### ISSUE THREAD

**Issue by ryans1230** [grandwazir/BanHammer#38]
Every time I try to purge someone's records, I get "PURGECOMMAND.PURGED" on the return. I am OP and every other command works.  We are a 1.3.2 server and I've tried reloading the plugin, the server, everything.

**Comment by grandwazir** [comment]
This just means the translation is missing. The command still works just you do not get the feedback to tell you what it has done.

**Comment by ryans1230** [comment]
Just tried it and the person still has a record... It does not affect database.
