### ISSUE TITLE
Database inbuilt in plugin and not use the Bukkit one?

### ISSUE THREAD

**Issue by ghost** [grandwazir/BanHammer#4]
G'day, 
Do you think its possible for you ta add your own database settings in the config and not use the bukkit ones? I know this might be hard but I have used many others that do, only because this is the only plugin I have that actually need to connect to a database online because of my ban list on my site and I now have to have all of my plugins that use the bukkit database on there.
And if you cant do this well It's fair enough.

Absolutely brilliant plugin tho :D

Cheers, Hayden.

**Comment by grandwazir** [comment]
I think you maybe able to define plugin specific settings in the bukkit.yml. There are no plans to seperate the configuration sorry.
