### ISSUE TITLE
Another Purge Problem

### ISSUE THREAD

**Issue by ryans1230** [grandwazir/BanHammer#43]
We are now getting an internal error message when trying to purge players with a history. It throws a "player has no bans" if they don't have any bans on record, but when we try a player with bans, we get an internal error message (tested on multiple players).

**Comment by grandwazir** [comment]
You will need to provide more detail for me to be able to help you. Copy and paste the error that appears in the server log.

**Comment by ryans1230** [comment]
I just got it to work on a banned player with two records. Yet it won't work on expired bans. As time goes on, it appears that it can purge some records but not other. I don't know what would cause this.  

Server log: http://pastebin.com/1VrxdkSa

**Comment by grandwazir** [comment]
I think this is due to the cascading option I added a while back. I'll look into this further.
