### ISSUE TITLE
BanHammer.ban.x permissions are broken

### ISSUE THREAD

**Issue by MarioG1** [grandwazir/BanHammer#46]
If i give my moderators banhammer.ban and banhammer.ban.long they can still ban longer than the specified time in the config file.

Bukkit: 1.4.7 R1.0
BanHammer: 2.0.4
Permissiosn:  PermissionsBukkit v2.0

**Comment by grandwazir** [comment]
Thanks for reporting this bug. I will investigate it this weekend.
