### ISSUE TITLE
Problem with banhammer.ban.short

### ISSUE THREAD

**Issue by ArtificialTruth** [grandwazir/BanHammer#48]
So if you give a group the permission banhammer.ban.short they still can't use
/ban testplayer t:short reason

**Comment by grandwazir** [comment]
Turn debugging on and it will tell you what permission you are missing.

**Comment by ArtificialTruth** [comment]
Can i do this ingame? or do need to restart the server?

**Comment by grandwazir** [comment]
You change it in your config.yml then restart the server.

**Comment by ArtificialTruth** [comment]
Hmm ill try on a test server then. brb. Can't close my main server down

**Comment by ArtificialTruth** [comment]
Get ''You are not allowed to do that''

**Comment by ArtificialTruth** [comment]
I tried to give the permission banhammer.ban to the group and banhammer.ban.short
Then i can ban more than the limit defined for banhammer.ban.short

**Comment by grandwazir** [comment]
Have you got the latest version? This bug was fixed in 2.0.5.

**Comment by ArtificialTruth** [comment]
ban-hammer-2.0.5 yup

**Comment by grandwazir** [comment]
Can you post the output of your server log when debugging and you run the command please.

**Comment by ArtificialTruth** [comment]
2013-02-24 17:26:26 [INFO] TheOnlyRealTGS issued server command: /ban test t:short
2013-02-24 17:26:26 [FINE] [BanHammer] <BukkitPermissionManager> Checking if permissible has banhammer.ban.

**Comment by ArtificialTruth** [comment]
I need the permission banhammer.ban. ?

**Comment by grandwazir** [comment]
They should only be able to ban higher than the limit in two situations. 1) if they have ban hammer.ban.\* 2) if they are an operator since they get all permissions by default. Can you post the relevant section of your permissions file?

**Comment by ArtificialTruth** [comment]
Admin:
    default: false
    permissions:
    - banhammer.ban
    - banhammer.ban.short
    - coloredTexts.group.aqua
    - spleef.join.1
    - sg.arena.join
    - sg.arena.vote
    - sg.lobby.join
    - sg.arena.nocmdblock
    - banhammer.history.*
    - banhammer.kick
    - banhammer.pardon.*
    - banhammer.notify
    - simpleprefix.admin
    - cleanchat.exempt
They aint op

**Comment by ArtificialTruth** [comment]
So how to fix this?

**Comment by grandwazir** [comment]
What permission plugin you using?

**Comment by ArtificialTruth** [comment]
PEX

**Comment by ArtificialTruth** [comment]
Could that be the problem? And does it work for you?

**Comment by grandwazir** [comment]
I can duplicate this issue now. I am working on a fix.

**Comment by grandwazir** [comment]
Now works in the latest version. Was an issue with all limits defaulting to true when you gave someone the banhammer.ban node. Changed so the node defaults them all to false. Thanks for reporting this issue and your patience.

**Comment by ArtificialTruth** [comment]
Np and thanks for fixing it
