### ISSUE TITLE
Missing permission?

### ISSUE THREAD

**Issue by SpaZMonKeY777** [grandwazir/BanHammer#50]
So in previous versions of BanHammer, I was able to negate the permission '- banhammer.notify' so that my non-staff players wouldn't see broadcast messages when a players kicked/banned. Did this get removed? Is there some other way to disable this permission?

This happened after upgrading to 2.1.0.

**Comment by grandwazir** [comment]
It has not been removed, just I have not included it the documentation yet. Has your old setup stopped working? I'll see if I can duplicate it.

**Comment by grandwazir** [comment]
This has been tested as working on 2.1.0. I would think this is a problem with your permission setup rather than a bug in BanHammer. I would contact whoever makes your permission plugin to find out how to nullify a permission node for a player.

**Comment by grandwazir** [comment]
Having looked into this more carefully it is indeed a bug in BanHammer. It has now been fixed. Thank you for reporting this bug and for your patience.
