### ISSUE TITLE
Permissions are broken (PermissionsEX)

### ISSUE THREAD

**Issue by MarioG1** [grandwazir/BanHammer#51]
If i give my moderators banhammer.ban and banhammer.ban.long they can still ban people longer than the specified time. Even if i give them only banhammer.ban.long they can ban people.

PEX: 1.19.5
Bukkit: #2742
Banhammer: 2.1.0

**Comment by grandwazir** [comment]
Hi Mario, this is intentional. Please see [this page](http://grandwazir.github.io/BanHammer/getting_started.html#permissions) for more information.

`banhammer.ban` functions as `banhammer.ban.*` used to do. If you only want someone to ban for a long time just give them `banhammer.ban.long`.

**Comment by MarioG1** [comment]
Thx for the info i didn't read the change log last time.

But there is still a bug if you only have banhammer.ban.long and you set the limit for long to 10 days you can't ban people for 11 days but you can ban people permanent (specify no time).

**Comment by grandwazir** [comment]
I'll double check this tomorrow.
