### ISSUE TITLE
Permissions problem

### ISSUE THREAD

**Issue by ArtificialTruth** [grandwazir/BanHammer#58]
I have these permissions:
    - banhammer.check
    - banhammer.history
    - banhammer.ban.*
    - banhammer.history.*
    - banhammer.kick
    - banhammer.pardon.*
    - banhammer.notify

I can't perm ban i the new version. Could in last version.

**Comment by grandwazir** [comment]
This is by design. Please see this change log: http://grandwazir.github.io/BanHammer/versions/2.1.0.html

You need to give yourself `banhammer.ban`; `banhammer.ban.*` is no longer a valid node.

**Comment by ArtificialTruth** [comment]
Okay
