### ISSUE TITLE
Load up error:

### ISSUE THREAD

**Issue by MAXIMUSSPRIME** [grandwazir/BanHammer#60]
Hello, every time I run BanHammer I get this error:

22.05 10:38:39 [Server] SEVERE at net.minecraft.server.v1_5_R3.ThreadServerApplication.run(SourceFile:573)
22.05 10:38:39 [Server] SEVERE at net.minecraft.server.v1_5_R3.MinecraftServer.run(MinecraftServer.java:410)
22.05 10:38:39 [Server] SEVERE at net.minecraft.server.v1_5_R3.MinecraftServer.q(MinecraftServer.java:477)
22.05 10:38:39 [Server] SEVERE at net.minecraft.server.v1_5_R3.DedicatedServer.r(DedicatedServer.java:227)
22.05 10:38:39 [Server] SEVERE at net.minecraft.server.v1_5_R3.DedicatedServer.an(DedicatedServer.java:262)
22.05 10:38:39 [Server] SEVERE at org.bukkit.craftbukkit.v1_5_R3.CraftServer.dispatchServerCommand(CraftServer.java:512)
22.05 10:38:39 [Server] SEVERE at org.bukkit.craftbukkit.v1_5_R3.CraftServer.dispatchCommand(CraftServer.java:523)
22.05 10:38:39 [Server] SEVERE at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:189)
22.05 10:38:39 [Server] SEVERE at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:23)
22.05 10:38:39 [Server] SEVERE at org.bukkit.Bukkit.reload(Bukkit.java:185)
22.05 10:38:39 [Server] SEVERE at org.bukkit.craftbukkit.v1_5_R3.CraftServer.reload(CraftServer.java:605)
22.05 10:38:39 [Server] SEVERE at org.bukkit.craftbukkit.v1_5_R3.CraftServer.enablePlugins(CraftServer.java:264)
22.05 10:38:39 [Server] SEVERE at org.bukkit.craftbukkit.v1_5_R3.CraftServer.loadPlugin(CraftServer.java:282)
22.05 10:38:39 [Server] SEVERE at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:381)
22.05 10:38:39 [Server] SEVERE at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:457)
22.05 10:38:39 [Server] SEVERE at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:217)
22.05 10:38:39 [Server] SEVERE at name.richardson.james.bukkit.banhammer.utilities.plugin.AbstractPlugin.onEnable(AbstractPlugin.java:103)
22.05 10:38:39 [Server] SEVERE at name.richardson.james.bukkit.banhammer.BanHammer.loadConfiguration(BanHammer.java:137)
22.05 10:38:39 [Server] SEVERE at name.richardson.james.bukkit.banhammer.BanHammer.hookAlias(BanHammer.java:232)
22.05 10:38:39 [Server] SEVERE at name.richardson.james.bukkit.alias.Alias.getHandler(Alias.java:89)
22.05 10:38:39 [Server] SEVERE at name.richardson.james.bukkit.alias.AliasHandler.<init>(AliasHandler.java:41)
22.05 10:38:39 [Server] SEVERE at name.richardson.james.bukkit.alias.Alias.getDatabase(Alias.java:55)
22.05 10:38:39 [Server] SEVERE java.lang.NullPointerException
22.05 10:38:39 [Server] INFO Using Alias v1.3.0.
22.05 10:38:39 [Server] INFO Enabling BanHammer v2.2.0
22.05 10:38:39 [Server] INFO Version 2.5-b665 (API v18) Enabled - By Rigby, fernferret, lithium3141 and main--

It seems to have to do with Alias, and is disabling a lot of the BanHammer functions, please help as soon as you can!

**Comment by grandwazir** [comment]
Does removing Alias solve the problem?

**Comment by MAXIMUSSPRIME** [comment]
Yes sir, no errors without Alias.

**Comment by MAXIMUSSPRIME** [comment]
I'd still like to use Alias though, I don't want it removed forever.

**Comment by grandwazir** [comment]
I use Alias myself as well. I will look into it shortly.

**Comment by MAXIMUSSPRIME** [comment]
Still getting this error, any luck with it?

Error:
http://pastebin.com/XVjtFuYs

**Comment by grandwazir** [comment]
I've identified the problem and will issue an update to Alias shortly.

**Comment by grandwazir** [comment]
Since this is a bug with Alias I am going to close this issue.
