### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by ArtificialTruth** [grandwazir/BanHammer#62]
On startup:
http://pastebin.com/8gnbZuj8

**Comment by grandwazir** [comment]
This should not happen on 2.2.5. Try that and see if it happens again.

**Comment by ArtificialTruth** [comment]
I used that version

**Comment by grandwazir** [comment]
Are you sure since the log says "Plugin BanHammer v2.2.1 generated an exception while executing task 25"

**Comment by ArtificialTruth** [comment]
Ooops i read your message wrong xD
Sorry for that
