### ISSUE TITLE
Error on plugin enalbe

### ISSUE THREAD

**Issue by MarioG1** [grandwazir/BanHammer#63]
Banhammer Version: 2.2.5
Bukkit: 1.5.2 R0.1

http://pastebin.com/gwywNER6

**Comment by grandwazir** [comment]
I'll need your database.yml (without password of cause) to see what the issue is. If it is blank I'll need the relevant bit from bukkit.yml.

**Comment by MarioG1** [comment]
The problem only occurs if you use the default bukkit settings for an file based sql database if you change it to an mysql database the error is gone.
