### ISSUE TITLE
Could not pass PlayerLoginEvent to BanHammer 2.2.5

### ISSUE THREAD

**Issue by CyanLights** [grandwazir/BanHammer#65]
Since updating the plugin, this happens every time someone joins:

http://pastebin.com/RRy9qdSj

We are experiencing a really weird bug where the user is able to send messages to the server, but they don't appear in their client chat for a good 30-45 seconds after they log in. I don't know if this is caused by BanHammer, AuthMe or another plugin, but I just wanted to throw that out there.

Thanks as always.

Edit: I also installed Alias at the same time.

**Comment by grandwazir** [comment]
Sorry I didn't reply to this. Let me know if this happens with the latest version of BanHammer. If it does, feel free to reopen this ticket.
