### ISSUE TITLE
[Strongly want fix] Problems with fixed dev version

### ISSUE THREAD

**Issue by ArtificialTruth** [grandwazir/BanHammer#71]
Seems like banned players can't join now, but this happens
http://dev.bukkit.org/bukkit-plugins/banhammer/?comment=265

EDIT: /bh recent works the oppisite way so you see the first bans (Only thing i know is you dont see the recent bans not quiet sure)

This is the version:
http://repository.james.richardson.name/snapshots/name/richardson/james/bukkit/ban-hammer/2.2.6-SNAPSHOT/

**Comment by grandwazir** [comment]
It would help me greatly if you only report one bug per issue as I do not get email notifications when someone edits a ticket. The issue with banned players being able to join is a problem with temporary bans being made with a version > 2.2.0 and < 2.2.6. See https://github.com/grandwazir/BanHammer/commit/db5ea342fcaf19fb22bfdaa8ce82342e33ab3cc1 for details. It should fix itself over time. For now just ban them again.

I'll look into the issue with /bh recent.
