### ISSUE TITLE
Reload database command

### ISSUE THREAD

**Issue by jaboy** [grandwazir/BanHammer#75]
Hey im running ban hammer in mysql.

sometimes i have to go in and delete/edit a ban, but the problem is that it may take a long time before the change is visible in the servers, so i would request a command maybe called bh reload to reload all bans (and maybe also config)

can this be done ?

thanks :3

**Comment by grandwazir** [comment]
This is due to the caching used by the plugin to speed up look up times. A better solution than a reload command which you will need to call every time would be an option to disable the cache completely. I'll see if that is possible in the next release.

**Comment by grandwazir** [comment]
For your information, making any changes to the database within the game will invalidate the cache.

**Comment by jaboy** [comment]
yea, i know that, and thats the problem :P

**Comment by grandwazir** [comment]
This is getting pushed back until 2.4.0.

**Comment by grandwazir** [comment]
Caching has been disabled for a while now due to another show stopping bug so this should no longer be an issue. Let me know if it still is.
