### ISSUE TITLE
Plugin won't start.

### ISSUE THREAD

**Issue by keremnc** [grandwazir/BanHammer#76]
Everytime I try to start up the server, the plugin gives an error: http://pastebin.com/ZAE13cTL
Only happens on some computers.

**Comment by keremnc** [comment]
I'm getting this after updating:org.bukkit.plugin.InvalidPluginException: java.util.MissingResourceException: Can't find localisation.banhammer.BanHammer bundle

**Comment by grandwazir** [comment]
Looking at the file name of the jar, you are not attempting to load two instances of BanHammer at once are you?

**Comment by keremnc** [comment]
No, I am only loading one instance.

**Comment by keremnc** [comment]
Sorry my plugin developer was incorrectly using the API.
