### ISSUE TITLE
Suggestion: Add silent parameter to kick & ban commands

### ISSUE THREAD

**Issue by ProjectInfinity** [grandwazir/BanHammer#78]
Could you implement a silent parameter so it doesn't broadcast an action when you'd like it to be quiet? I.e. /ban Notch -s t:2d Reasoning.

Many plugins do this already, like CommandBook does not announce certain commands if "-s" is applied to the command. This would be nice because there may be a time when you do not wish every player to see a ban or kick message.

**Comment by grandwazir** [comment]
This is something I am looking to support although it will require a slight refactoring of BukkitUtilities to support it. The underlying support for silent bans is already there just not used by BanHammer at the moment.

**Comment by grandwazir** [comment]
I've also added add a feature to allow pardons to be silent as well.

**Comment by ProjectInfinity** [comment]
Great!
