### ISSUE TITLE
Reason suffix

### ISSUE THREAD

**Issue by deanveloper** [grandwazir/BanHammer#79]
I would like to make it so that whenever I ban someone, I can add a suffix to the ban. Sometimes chat doesn't add enough space for me to type "appeal: <appeal link>"

If you could add a suffix for reasons in the config, that would be great!

**Comment by grandwazir** [comment]
You can customize all the messages already by changing the localisation files within the plugin. See this page for more information: https://github.com/grandwazir/BukkitUtilities/wiki/Localisation

**Comment by deanveloper** [comment]
Thanks for the info!
