### ISSUE TITLE
Suggestion: When a player is banned, put them into a group

### ISSUE THREAD

**Issue by deanveloper** [grandwazir/BanHammer#81]
I just thought of something. I really wanted to make it so that if a player was banned, it would say so on my website. I can only get this to work if I put them into a group. If you would be kind enough to add this as a feature, that would be awesome!

**Comment by grandwazir** [comment]
BanHammer does not support this directly however you could write a plugin that listens to the BanHammer events to do this for you. Every time a player is banned it sends an event called 'BanHammerPlayerBannedEvent'. Your plugin would need to listen to this event and then place the player that was banned in the right permission group. 

To do the reverse just listen to 'BanHammerPlayerPardonedEvent'. The one downside to this is when bans expire an Pardon event is not fired. This means that the plugin would also have to check every so often to expired bans.

**Comment by grandwazir** [comment]
I am going to close this issue now since this due to the number of permission plugins out there it is not something I will be adding as standard.
