### ISSUE TITLE
Errors for 1.6.2

### ISSUE THREAD

**Issue by ArtificialTruth** [grandwazir/BanHammer#82]
http://pastebin.com/pqD2w21i
http://pastebin.com/fPEx7xcR

Using:
http://repository.james.richardson.name/snapshots/name/richardson/james/bukkit/ban-hammer/2.3.0-SNAPSHOT/

**Comment by grandwazir** [comment]
I think this is a database issue. Could you please turn debugging on. You can do this by going to config.yml and setting LOGGING to ALL. It is a bit noisy but if you can keep it on until it happens again then send me the log it would be helpful.

**Comment by ArtificialTruth** [comment]
Note this don't happen all the time. I can't, since i need to stop my server with 80+ online. You need to add a /bh reload command for the config

**Comment by grandwazir** [comment]
When you next restart your server you will need to turn debugging on if I am to resolve this issue. Either that or send me a copy of your database.

**Comment by ArtificialTruth** [comment]
https://dl.dropboxusercontent.com/u/38640291/BanHammer.db

**Comment by grandwazir** [comment]
I am struggling to debug this further. Looking through the database you attached williamalder has never been banned. I don't think he is the one triggering the error. I'll need the details of what happens when someone logs in with debug mode on, or the name of a person who consistently causes this issue.

**Comment by grandwazir** [comment]
I have now found out what is causing this. Please see #86 for more details. I am closing this issue so I can keep everything related to it in the same thread.
