### ISSUE TITLE
Permissions problem

### ISSUE THREAD

**Issue by ArtificialTruth** [grandwazir/BanHammer#83]
Some users reporting about they can't temp ban anymore. The person tried to ban a player for 1 day
Permissions the mod have:
    - banhammer.check
    - banhammer.ban.warning
    - coloredTexts.group.red
    - banhammer.history.*
    - banhammer.kick
    - banhammer.pardon.*
    - banhammer.notify
Some errors in the console:
http://pastebin.com/JcbBrFg5

No errors when he tried to ban the guy though

version 2.3.0

**Comment by grandwazir** [comment]
The exception looks like a database issue. Could you send me a copy of your database please. As for the other issue, check your config.yml, I think I renamed ban-limits to limits. just renamed your old ban-limits to limits to fix the issue.

**Comment by ArtificialTruth** [comment]
https://dl.dropboxusercontent.com/u/38640291/BanHammer.db

**Comment by grandwazir** [comment]
The permission issue I assume you solved. The other bug is the same as #86. I am closing all other issues related to it, except #86 to make it easier for me.
