### ISSUE TITLE
Banned players can still join

### ISSUE THREAD

**Issue by ArtificialTruth** [grandwazir/BanHammer#84]
This error comes right before a temp banned player joins:
http://pastebin.com/ZcXHzBAu

**Comment by grandwazir** [comment]
Could you turn on debugging please and post the log.

**Comment by ArtificialTruth** [comment]
K ill try to remember it

**Comment by grandwazir** [comment]
I need the name of the player at least to debug this further.

**Comment by grandwazir** [comment]
I know what this is now and I am going to close this issue so I can track things all in the same thread. See #86 for more details.
