### ISSUE TITLE
Banned players joining

### ISSUE THREAD

**Issue by Nistune** [grandwazir/BanHammer#86]
Using Spigot build 1080 for 1.6.2, decided to try the snapshot on a new testserver, so its a clean install of everything.

Kicks work good, all of the commands appear to work until you ban someone and the banned person joins. Process to get this was:

/ban Kaval test

Seems to work, her name shows up in /bh check Kaval as perm banned. But, user joins:

http://pastebin.com/mUPkYnfw

After the banned player has joined the plugin seems to stop working completely except for kicks:

8:42:30 PM CONSOLE: [INFO] Nistune issued server command: /bh check kaval
8:42:30 PM CONSOLE: [SEVERE] null
8:42:30 PM CONSOLE: exception executing command 'bh' in plugin BanHammer v2.3.0-SNAPSHOT

Im assuming this is to do with spigot, while I get spigot isnt official, I have been using older versions of  banhammer with spigot for 4+ months and a lot of other servers also use it. Would be a complete bitch to have to change banning plugins (Banhammer is the best I know of) 

If you need more info I will be happy to help!

EDIT: Put on logging to ALL and tried out a few commands again, got the banned player to join:

http://pastebin.com/V1Nj8ABr

**Comment by grandwazir** [comment]
I use Spigot myself so I have a vested interest it making sure it works on that platform. I can't see the full stack trace from the log you gave me which is missing, crucially, the line that caused the error.

I have found one bug from doing a quick review of that code. If you server is operating in online mode it would check to see if someone was banned twice. That might cause some issue in the future so I'll fix it now. Would not explain why the check command is returning null though.

I'll look into this further. Thank you for your report. If you can get me a proper stack trace when the plugin is in debugging mode that would be great.

**Comment by grandwazir** [comment]
I can't duplicate it on my development machine, however after doing some research I have found out what the bug is. It is an old bug in the persistence library shipped with Bukkit but unfortunately Bukkit still ships the old version. I've [asked them](https://bukkit.atlassian.net/browse/BUKKIT-4709) to update.

 I think my latest patch will work around this but since I can't get the problem to occur could you download the [latest snapshot](http://repository.james.richardson.name/snapshots/name/richardson/james/bukkit/ban-hammer/2.3.0-SNAPSHOT/ban-hammer-2.3.0-20130816.232239-2.jar) and test it for me?

**Comment by Nistune** [comment]
Downloaded the snapshot, banned user can still join/getting errors:

http://pastebin.com/E5QqiSE1

Decided to remove everything but banhammer/spigot:

http://pastebin.com/3pe1fWvK

http://pastebin.com/ewH9QY97

Switched back to version 2.2.0 just to make sure its not something else and its leaving people banned:

http://pastebin.com/S3Xhkivq

Hope this helps :)

**Comment by grandwazir** [comment]
Please try this [build](http://repository.james.richardson.name/snapshots/name/richardson/james/bukkit/ban-hammer/2.3.0-SNAPSHOT/ban-hammer-2.3.0-20130817.090722-3.jar) and see if that fixes the problem. I have decided to disable the caching system until the library is updated in Bukkit.

**Comment by Nistune** [comment]
Players are staying banned now, not seeing any error messages.  

http://pastebin.com/tQ2xgpvu

Had to ban myself through console since my test subject is away. But tested banning/pardoning someone else from on the server:

http://pastebin.com/bV1zjt80

Im not getting any error messages, an odd thing was when I pardoned Kaval it said she had been pardoned twice. 

The only bug I am getting is when I use /bh history on 'Kaval' after she has been banned and pardoned it says she has no ban history, wasnt sure if this was to do with the caching system, if so ignore this,

http://pastebin.com/UsEPy1Cd

Again, thanks for the great plugin, I dont mind testing further if you need it!

**Comment by grandwazir** [comment]
I am going to assume this is fixed now. Thank you for testing.
