### ISSUE TITLE
java.util.MissingResourceException: Can't find localisation/BanHammer bundle

### ISSUE THREAD

**Issue by captbunzo** [grandwazir/BanHammer#87]
I am having the same problem that soysuva is experiencing.

http://pastebin.com/DbPm24i0

I am experiencing a very similar problem with your Alias plugin.

I am running Ubuntu 13.04 with Java version as follows:

nyvaria@ziggy:~/server-test/logs$ java -version
java version "1.7.0_25"
Java(TM) SE Runtime Environment (build 1.7.0_25-b15)
Java HotSpot(TM) 64-Bit Server VM (build 23.25-b01, mixed mode)

I have tried removing all other plugins and still experience the error on startup. Note that I am using Spigot.

Let me know what else I can try or what information I can provide.

(and of course, thanks for the plugins!)

**Comment by grandwazir** [comment]
I'll see if I can duplicate the issue here.

**Comment by grandwazir** [comment]
I've confirmed this issue using both CraftBukkit and Spigot on Windows. Will see if I can duplicate it on my linux machine.

**Comment by NewBestX** [comment]
I have the same error using craftbukkit on windows or linux...
This plugin is very important to my server, so I hope you can find a solution very soon...

**Comment by grandwazir** [comment]
Doesn't crash on my development machine which is running the same version of Java.

**Comment by grandwazir** [comment]
This appears to be a classloader issue. This should not happen since I already test for if the resourcebundle exists before loading to avoid exactly this kind of issue. What I think is happening is while the bundle is available to the class loader testing the resource exists, the actual logger uses a different classloader.

**Comment by grandwazir** [comment]
Please try the following [build](http://repository.james.richardson.name/snapshots/name/richardson/james/bukkit/ban-hammer/2.3.1-SNAPSHOT/ban-hammer-2.3.1-20130827.184502-1-shaded.jar) and tell me if it fixes the issue for you..

**Comment by captbunzo** [comment]
Thanks for your time on this today. I've just tried the build and it has fixed the issue. I did get the following message:

21:30:38 [INFO] [BanHammer] Enabling BanHammer v2.3.1-SNAPSHOT
21:30:38 [WARNING] [BanHammer] saving-default-configuration
21:30:38 [WARNING] [BanHammer] invalid-configuration-value
21:30:38 [WARNING] [BanHammer] invalid-configuration-value

But it loaded fine. Of course, I am still getting the same problem with Alias, but I'm sure that'll require a build of it's own to fix.

**Comment by grandwazir** [comment]
Yes it will. They both share a common library but having already descended into classpath madness and survived each plugin I ship now has it's own shaded instance to avoid any issues.

I've fixed this bug and those untranslated messages in 2.3.1 which is available to download from the repository.

I've also released an updated version of Alias with the same fix.

**Comment by grandwazir** [comment]
Actually hold out on Alias. There is still a nasty bug in it I need to squash.

**Comment by captbunzo** [comment]
Any news on when this fix may come to Alias?
