### ISSUE TITLE
Suggestion: Add alias for pardoning.

### ISSUE THREAD

**Issue by ProjectInfinity** [grandwazir/BanHammer#88]
I suggest adding the alias "unban" to the pardon command that BanHammer utilizes.

Add to plugin.yml under pardon command:
aliases: [unban]

**Comment by grandwazir** [comment]
I try to limit doing this as much as possible since it tends to conflict with other plugins. Can you not make the alias yourself in bukkit.yml nowadays?

**Comment by ProjectInfinity** [comment]
I don't use this plugin anymore, but for the sake of those who are. I highly recommend doing this, simply because ALIASES are nothing more than aliases. If another plugin wants the command, it will overwrite the alias. 
Besides, why should you accommodate for server owners who are dumb enough to run several plugins offering the same feature?

**Comment by grandwazir** [comment]
Well in that case I'll add it on to the improvement list.
