### ISSUE TITLE
Two problems.

### ISSUE THREAD

**Issue by coltensplat** [grandwazir/BanHammer#89]
I am using version 2.3.1
There are 2 problems I have run into.
1.) When I try to purge someone's bans, I receive an internal error message.
2.) When I use /bh audit, I receive the same internal error. I tried a complete reinstall of the plugin (ie directories and jar files) and nothing works. I haven't tried an earlier version but I will soon.
Thank you in advance,
Coltensplat

**Comment by coltensplat** [comment]
Update: now this is happening with every command. Can't seem to fix it myself

**Comment by grandwazir** [comment]
You need to look inside your server.log. It will give you information I need to help you fix whatever problem has occurred.

**Comment by coltensplat** [comment]
Sorry I couldn't respond. The problem has been resolved, I figured it was a broken file I had forgotten to delete. Thanks for responding though.
-coltensplat
