### ISSUE TITLE
Ban limits are broken.

### ISSUE THREAD

**Issue by ArtificialTruth** [grandwazir/BanHammer#91]
A guy in the group Mods can perm ban by typing /ban test testreason
Even though he have these perms:
    - banhammer.check
    - banhammer.ban.warning
    - banhammer.history.*
    - banhammer.kick
    - banhammer.pardon.*
    - banhammer.notify

Config:
  warning: 1d
  short: 2d
  medium: 3d
  long: 8d

**Comment by grandwazir** [comment]
I keep fixing this, it is starting to get annoying. I'll look into why this is happening this weekend.

**Comment by ArtificialTruth** [comment]
Thanks! :smile:
