### ISSUE TITLE
Time on the ban screen is always in the the system language

### ISSUE THREAD

**Issue by MarioG1** [grandwazir/BanHammer#95]
![image](https://f.cloud.github.com/assets/1714042/1893524/0a6518e4-7a9d-11e3-9474-e4e5999ce75f.png)

Is it possible to change the language of the "in 24 Stunden" to English or is banhammer always using the system language for this?

**Comment by grandwazir** [comment]
It currently uses the default locale provided by the JVM. If you are on a German server it is most likely going to be German. You can force a different locale when you run Bukkit initially. 

See http://stackoverflow.com/questions/64038/setting-java-locale-settings for more information.

**Comment by MarioG1** [comment]
Thx. I'll try it out :)

**Comment by grandwazir** [comment]
I'll assume this is fixed now.
