### ISSUE TITLE
Startup error

### ISSUE THREAD

**Issue by NewBestX** [grandwazir/BanHammer#96]
http://pastebin.com/QA4Dwunh

Using banhammer 2.3.1 and craftbukkit Beta 1.7.2 R 0.2

**Comment by NewBestX** [comment]
I downloaded bukkit build 2999 and seems to work fine now :D

**Comment by grandwazir** [comment]
I am glad it is working now. It looks like it was a network issue when the updater was trying to retrieve details about any new versions.
