### ISSUE TITLE
Ban limits are broken.

### ISSUE THREAD

**Issue by ArtificialTruth** [grandwazir/BanHammer#97]
The permission group mods can perm ban even though they only have those perms:

```
    - banhammer.ban.warning
    - banhammer.history.*
    - banhammer.pardon.*
```

My config:

```
debugging: false
automatic-updates:
  enabled: true
  method: NOTIFY
  branch: STABLE
ban-limits:
  warning: 1d
  short: 2d
  medium: 5d
  long: 8d
immune-players: {}
alias-plugin:
  enabled: true
logging: INFO
undo-time: 1m
```

Probably related to this: https://github.com/grandwazir/BanHammer/issues/91
Using v. 2.3.1

**Comment by grandwazir** [comment]
This should be fixed in the development build I just uploaded to DevBukkit. Please try it and tell me if it fixes the issue for you.

**Comment by ArtificialTruth** [comment]
Alright gonna download it now and upload it to my server. If i put this jar in and don't delete the old one, will it load the newest version?

**Comment by ArtificialTruth** [comment]
Alright i tested the version, now they can't ban at all.

**Comment by MarioG1** [comment]
I have a similar/same problem.

If you use /ban name t:5d reason the player is banned permanent. This is also the reason why players with  banhammer.ban.<limit> can't ban at all.

**Comment by grandwazir** [comment]
@MarioG1 Your issue is a syntax problem. It is assuming that the reason is what comes after the player's name. To fix this just put the time before the name. In the new version this is fixed.

@TheOnlyRealTGS I have tested this on the new build and it works correctly so I will close this issue now.

**Comment by ArtificialTruth** [comment]
Okay, i'll test it!

**Comment by grandwazir** [comment]
You can test this build for me if you like? It is at: http://repository.james.richardson.name/snapshots/name/richardson/james/bukkit/ban-hammer/2.3.2-SNAPSHOT/ban-hammer-2.3.2-20140417.204406-2-shaded.jar

**Comment by ArtificialTruth** [comment]
Okay, that version is seriously broken. EVERYBODY can kick!
