### ISSUE TITLE
Temp bans don't work. Period.

### ISSUE THREAD

**Issue by remiscarlet** [grandwazir/BanHammer#98]
I feel that this is related to the already documented issue of temporary ban permissions not working, but this seems different because any temporary bans are now entirely broken. Eg,

/ban remi_scarlet t:3d test

Will ban permanently, even from ops and from console itself, implying that it's definitely not a permission issue. There aren't any logs or errors so perhaps there's an error in parsing the commands or the like - was anything drastically changed when you fixed the punctuation checks for ban reasons?

**Comment by grandwazir** [comment]
What version are you using?

**Comment by remiscarlet** [comment]
Latest one available on Bukkit, 2.3.2-SNAPSHOT.

**Comment by ayyy** [comment]
BukkitUtils had changed the way stuff works, apparently. Took me a while to figure it out as none of this is documentated.

You have to do:
/ban remi_scarlet **-t** t:3d test

**Comment by grandwazir** [comment]
You should not have to do that - it is a bug in BukkitUtils. I'll look at
it this weekend.

**Comment by remiscarlet** [comment]
Hi!

Was wondering if you've had a chance to check out the reasons for tempbans not working.

**Comment by grandwazir** [comment]
I am looking at it today and hoping to have a build out this evening.

**Comment by grandwazir** [comment]
Your example command is now working correctly in the latest build. I have set it now so you have to put a "-" in front of argument options. This will mean that no longer will they be treated as part of the ban reason if you put them at the end.

**Comment by sillvva** [comment]
Could you update the instructions in the wiki to how it should be exactly now? It seems to still show the t without a -. So it appears to be based on an older version/snapshot.
