### ISSUE TITLE
cant use partial names to kick or ban

### ISSUE THREAD

**Issue by PiLoT-** [grandwazir/BanHammer#99]
if player w0rld-smith needs a kick or ban you have to type out full name or tab to complete it.

it used to match to whoever online whose name is closest

for instance if i was to type /kick w0 it would kick a player with that at start of his name

**Comment by grandwazir** [comment]
This was a deliberate change now you can tab complete and should not be much of an inconvenience. I think it is better that your intent is completely clear when issuing a command to kick or ban by asking for the full name.

**Comment by PiLoT-** [comment]
is it possiblt to re insert that possibilty, diable is by defaut but make it an option?
